export interface Job {
    jobTitle:string,
    jobType:string,
    careerLevel:string,
    experience:string,
    salary:string,
    jobCategories:string,
    jobDescription:string,
    jobRequirements:string,
    date:Date,
    id?:string,
    status:string,
    companyID?:string,
    educationLevel:string,
    jobTitleAR?:string,
    jobTypeAR?:string,
    careerLevelAR?:string,
    experienceAR?:string,
    salaryAR?:string,
    jobCategoriesAR?:string,
    jobDescriptionAR?:string,
    jobRequirementsAR?:string,
    educationLevelAR?:string,

}
